[mypy]
warn_unused_configs = True
ignore_missing_imports = True

[mypy-cerberus]
ignore_missing_imports = True

[mypy-sqlalchemy]
ignore_missing_imports = True

[mypy-snowflake.sqlalchemy]
ignore_missing_imports = True

[mypy-snowflake.sqlalchemy.pool]
ignore_missing_imports = True

[mypy-coloredlogs]
ignore_missing_imports = True
